server {
    listen 443 ssl;
    server_name disaster-watch.duckdns.org;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:8000/;
    }

    location /api/disaster/ {
        proxy_pass http://disaster-service:8000/;
    }

    location /api/chat/ {
        proxy_pass http://chatbot-service:8000/;
    }
}